#!/usr/bin/python3
from willyshandler import Willys
from database import Database

categories = {'Kott-chark-och-fagel/Fagel': 'fågel',
              'Kott-chark-och-fagel/Kott': 'kött',
              'Kott-chark-och-fagel/Korv': 'korv',
              'Kott-chark-och-fagel/Chark': 'chark',
              'Kott-chark-och-fagel/Palagg': 'pålägg',
              'Kott-chark-och-fagel/Delikatesschark': 'delikatesschark',
              'Frukt-och-Gront/Frukt': 'frukt',
              'Frukt-och-Gront/Farska-bar': 'bär',
              'Frukt-och-Gront/Gronsaker': 'grönsaker',
              'Frukt-och-Gront/Potatis-och-rotsaker': 'rotfrukt',
              'Frukt-och-Gront/Svamp': 'svamp',
              'Frukt-och-Gront/Kryddor-och-smaksattare': 'färska-kryddor',
              'Mejeri-ost-och-agg/Ost': 'ost',
              'Mejeri-ost-och-agg/Mjolk': 'mjölk',
              'Mejeri-ost-och-agg/Juice-fruktdryck-och-smoothie': 'fruktdryck',
              'Mejeri-ost-och-agg/Havre-Soja-Risdryck-mm': 'mejeri-övrigt',
              'Mejeri-ost-och-agg/Filmjolk-och-Yoghurt': 'yoghurt',
              'Mejeri-ost-och-agg/Kvarg-och-Cottage-cheese': 'kvarg',
              'Mejeri-ost-och-agg/Matlagning': 'matlagning',
              'Mejeri-ost-och-agg/Smor-margarin-och-jast': 'smör',
              'Mejeri-ost-och-agg/Agg': 'ägg',
              'Mejeri-ost-och-agg/Mellanmal-och-desserter': 'mejeri-dessert',
              'Mejeri-ost-och-agg/Vegetariskt': 'mejeri-veg',
              'Mejeri-ost-och-agg/Allergi': 'mejeri-allergi',
              'Skafferi/Konserver-och-burkar': 'konserver',
              'Skafferi/Oliver-och-delikatesser': 'delikatess-burkar',
              'Skafferi/Olja-och-vinager': 'olja',
              'Skafferi/Kryddor-och-smaksattare': 'kryddor',
              'Skafferi/Texmex': 'texmex',
              'Skafferi/Asien': 'asien',
              'Skafferi/Pasta-ris-och-matgryn': 'pasta',
              'Skafferi/Torra-baljvaxter': 'baljväxter',
              'Skafferi/Bakning': 'bakning',
              'Skafferi/Flingor-gryner-och-musli': 'musli',
              'Skafferi/Sylt-mos-och-marmelad': 'sylt',
              'Skafferi/Soppor-och-kramer': 'soppa',
              'Skafferi/Desserter-och-glasstillbehor': 'dessert',
              'Skafferi/Torkad-frukt': 'torkad-frukt',
              'Skafferi/Allergi': 'skafferi-allergi',
              'Brod-och-Kakor/Brod': 'bröd',
              'Brod-och-Kakor/Knackebrod-och-Skorpor': 'knäckebröd',
              'Brod-och-Kakor/Ris-och-majskakor': 'riskakor',
              'Brod-och-Kakor/Fastfoodbrod': 'fastfoodbrod',
              'Brod-och-Kakor/Kex-och-Kakor': '',
              'Brod-och-Kakor/Kondis-och-fika': '',
              'Brod-och-Kakor/Fryst': '',
              'Fryst/Kott-och-fagel': '',
              'Fryst/Kott-burgare-och-korv-mm': '',
              'Fryst/Fisk-och-skaldjur': '',
              'Fryst/Fardigmat': '',
              'Fryst/Portionsratter-och-snabblagat': '',
              'Fryst/Potatis': '',
              'Fryst/Gronsaker-och-kryddor': '',
              'Fryst/Bageri': '',
              'Fryst/Vegetariskt': '',
              'Fryst/Frukt-och-Bar': '',
              'Fryst/Glass': '',
              'Fryst/Allergi': '',
              'Fisk-och-Skaldjur/Fisk': '',
              'Fisk-och-Skaldjur/Skaldjur-och-Havsdelikatesser': '',
              'Fisk-och-Skaldjur/Lakeprodukter': '',
              'Fisk-och-Skaldjur/Kaviar-och-Rom': '',
              'Fisk-och-Skaldjur/Sill-Anjovis-och-Sardiner': '',
              'Fisk-och-Skaldjur/Palagg': '',
              'Vegetariskt/Tofu': '',
              'Vegetariskt/Snabblagat': '',
              'Vegetariskt/Palagg-och-ost': '',
              'Vegetariskt/Korv': '',
              'Vegetariskt/Fryst-vegetariskt': '',
              'Vegetariskt/Ovrigt-vegetariskt': '',
              'Glass-godis-och-snacks/Godis': '',
              'Glass-godis-och-snacks/Choklad': '',
              'Glass-godis-och-snacks/Presentforpackningar': '',
              'Glass-godis-och-snacks/Chips-snacks-och-dip': '',
              'Glass-godis-och-snacks/Nyttiga-snacks': '',
              'Glass-godis-och-snacks/Glass-och-tillbehor': '',
              'Glass-godis-och-snacks/Tuggummi': '',
              'Glass-godis-och-snacks/Halstabletter': '',
              'Dryck/Kaffe': '',
              'Dryck/Te-och-choklad': '',
              'Dryck/Lask': '',
              'Dryck/Sport-och-energidryck': '',
              'Dryck/Ol-och-cider': '',
              'Dryck/Vatten': '',
              'Dryck/Saft-och-stilldrinks': '',
              'Fardigmat': '',
              'Barn/Barnmat-och-fruktdryck': '',
              'Barn/Grot': '',
              'Barn/Valling-och-ersattning': '',
              'Barn/Blojor-': '',
              'Barn/Barnvard': '',
              'Barn/Bad-och-dusch': '',
              'Barn/Nappar-och-nappflaskor': '',
              'Barn/Barntillbehor': '',
              'Blommor': '',
              'Hem-och-Stad/Disk-och-stad': '',
              'Hem-och-Stad/Toalett-och-hushallspapper': '',
              'Hem-och-Stad/Tvatt': '',
              'Hem-och-Stad/Hushallsemballage': '',
              'Hem-och-Stad/Grill': '',
              'Hem-och-Stad/Koket/Kaffefilter': '',
              'Halsa-och-Skonhet/Harvard': '',
              'Halsa-och-Skonhet/Kroppsvard': '',
              'Halsa-och-Skonhet/Munvard': '',
              'Halsa-och-Skonhet/Nasdukar-och-bomull': ''
              }

def update(path):
    db = Database(path)
    willys = Willys()
    items = willys.scan(categories)
    db.bulk_put(items)

update('/home/ubuntu/database/willysdata.p')